apiVersion: kyverno.io/v2alpha1
kind: ClusterCleanupPolicy
metadata:
  name: cleandeploy
spec:
  match:
    any:
    - resources:
        kinds:
          - Deployment
        selector:
          matchLabels:
            canremove: "true"
  conditions:
    any:
    - key: "{{ time_since('','{{metadata.creationTimestamp}}','') }}"
      operator: GreaterThan
      value: "30s"
  schedule: "0 22 * * *"