apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-manifest-integrity    
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: verify-deployment-integrity
      match:
        any:
        - resources:
            kinds:
              - Deployment
      validate:
        manifests:
          attestors:
          - count: 1
            entries:
            - keys:
                publicKeys: |-
                  -----BEGIN PUBLIC KEY-----
                  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvvGmH01+5TbC22NZCKGq4LHIkYtD
                  ntdr/gv64JD8QyDC5pg/Ua4BT3lHuoh1bQOdUScnzYC+YvVNl8uWNVl11g==
                  -----END PUBLIC KEY-----  